### ISSUE TITLE
誤記報告: P195の作成するファイルの名前、P513のテスト実行コマンドについて

### ISSUE THREAD

**Issue by himadajin** [msyksphinz-self/support_ca_llvm_book#11]
P195のLLVMにテストを追加する箇所でファイル名の表記揺れがありました。
「simple_test.llというファイルを追加します」という説明と、添付されたコードのファイル名は"llvm/test/CodeGen/simple_test.ll"となっていました。一方で、llvm-litのコマンドを実行する説明以降の箇所ではファイル名が"simple_func.ll"となっていました。
この2つは同じファイルを指していると思われるので、simple_func.llが正しいのではないでしょうか？

つぎに、P513のllvm-litでRISCVのすべてのテストを実行する説明において、コマンドが
${BUILD}/bin/llvm-lit -v llvm-myriscvx120/test/CodeGen/RISCV
となっていましたが、testディレクトリはllvm-myriscv120/llvm以下にあるため
${BUILD}/bin/llvm-lit -v llvm-myriscvx120/llvm/test/CodeGen/RISCV
が正しいと思います。

別の意図があったり、誤記ではなかったら申し訳ありません。

**Comment by msyksphinz-self** [comment]
ありがとうございます。ご指摘の通りです。READMEの正誤表を更新しました。

**Comment by himadajin** [comment]
ご対応ありがとうございます。
