### ISSUE TITLE
誤記報告：P325の表5について

### ISSUE THREAD

**Issue by tichkr** [msyksphinz-self/support_ca_llvm_book#12]
R_MYRISCVX_LO12_Iなどの「LO12」が付く4つのリロケーション情報の説明が、全て「上位12ビット」となっています。「下位12ビット」の間違いではないでしょうか。
同様に、R_MYRISCVX_PCREL_LO12_IとR_MYRISCVX_PCREL_LO12_Sの説明が、「絶対アドレスの上位12ビット」となっています。1つ目の指摘も合わせて、「PC相対アドレスの下位12ビット」の間違いではないでしょうか。

**Comment by msyksphinz-self** [comment]
ありがとうございます。ご指摘の通りです。
正誤表に追記いたしました。

**Comment by tichkr** [comment]
ご対応ありがとうございます。
正誤表に、R_MYRISCVX_PCREL_LO12_IとR_MYRISCVX_PCREL_LO12_Sの絶対アドレスとPC相対アドレスの方が記載されておりませんでした。
ご確認よろしくお願いします。

**Comment by msyksphinz-self** [comment]
失礼しました。抜けておりました。ご確認をお願いします。
