### ISSUE TITLE
Chipyardのインストールについて

### ISSUE THREAD

**Issue by m1goh** [msyksphinz-self/support_ca_llvm_book#14]

**Comment by m1goh** [comment]
WSLのUbuntu20.04を使用しています。Chipyardをインストールしています。
spikeが動いたのでいいといえばいいのですが、Rocket-ChipとBOOMを動かしてみたいです。
本の78ページにしたがって次のコマンドを実行しました。

akiyoshi@beetle:~/chipyard$ cd sims/verilator/
akiyoshi@beetle:~/chipyard/sims/verilator$ make CONFIG=RocketConfig

次の様なエラーになりました。
Running with RISCV=/home/akiyoshi/riscv64_github
/home/akiyoshi/chipyard/common.mk:59: /home/akiyoshi/chipyard/generators/nvdla/nvdla.mk: No such file or directory
make: *** No rule to make target '/home/akiyoshi/chipyard/generators/nvdla/nvdla.mk'.  Stop.

rmしてしまったのですがveriilatorとJDK17をインストールして途中エラーがでましたがコマンドができました。
./simulator-chipyard-RocketConfig pk ~/gcd.riscvを実行しました。
結果はうまくいきませんでした。

また、veriilatorとJavaをインストールしてみるつもりですが、Rocket-ChipとBOOMを動かすにはどうしたらよいでしょうか？
教えていただけるとありがたいです。よろしくお願いします。

**Comment by msyksphinz-self** [comment]
エラーメッセージを見る限りですと、generatorディレクトリのsubrepoがダウンロードできていないかもしれません。
`./scripts/init-submodules-no-riscv-tools.sh`を実行して、`generators/`以下のディレクトリが正しくダウンロードできているか確認して頂けないでしょうか？

**Comment by m1goh** [comment]
回答をありがとうございます。./scripts/init-submodules-no-riscv-tools.shを実行して、generators/以下のディレクトリをダウンロードして以下のように実行しました。

akiyoshi@beetle:~/chipyard$ cd sims/verilator/
akiyoshi@beetle:~/chipyard/sims/verilator$ make CONFIG=RocketConfig
/home/akiyoshi/chipyard/common.mk:7: *** RISCV is unset. You must set RISCV yourself, or through the Chipyard auto-generated env file.  Stop.
akiyoshi@beetle:~/chipyard/sims/verilator$ ls ~/
chipyard  gcd.c  gcd.c~  gcd.dmp  gcd.riscv  gcd.sim.log  gcd.source.dmp  llvm-myriscv120  riscv  riscv64_github
akiyoshi@beetle:~/chipyard/sims/verilator$ export RISCV=${HOME}/riscv64_github
akiyoshi@beetle:~/chipyard/sims/verilator$ make CONFIG=RocketConfig

Javaを自動的にダウンロードしてインストールしてくれたようです。
以下のようなエラーがでて気にになりました。
 
error
[error] Picked up JAVA_TOOL_OPTIONS: -Xmx8G -Xss8M -Djava.io.tmpdir=/home/akiyoshi/chipyard/.java_tmp
[success] Total time: 84 s (01:24), completed Aug 16, 2022, 11:23:41 PM

以下のコマンドを実行してみました。

$ ./simulator-chipyard-RocketConfig  pk ~/gcd.riscv
This emulator compiled with JTAG Remote Bitbang client. To enable, use +jtag_rbb_enable=1.
Listening on port 40149
[UART] UART0 is here (stdin/stdout).
simulator-chipyard-RocketConfig: ../fesvr/htif.h:35: T htif_t::from_target(target_endian<T>) const [with T = long unsigned int]: Assertion `endianness == memif_endianness_little || endianness == memif_endianness_big' failed.
本の79ページの様にうまく動きません。どうしたらよいでしょうか？よろしくお願いします。

**Comment by msyksphinz-self** [comment]
ログを見る限りは、Verilatorのバイナリのビルド自体はあまり問題なさそうに見えます。
Javaのビルド時のエラーも、同様なものが出ていた気がするので問題はないと思います。

`gcd.riscv`はSpikeでのシミュレーションでも実行できることを確認されましたでしょうか？

```sh
$ spike pk ~/gcd.riscv
```

**Comment by m1goh** [comment]
回答ありがとうございます。
Spikeのシミュレーションは、こんな感じです。

```
akiyoshi@beetle:~$ spike pk ~/gcd.riscv
bbl loader
GCD(273, 21) = 21
GCD(411, 27117) = 3
```

BOOMでシュミレーションしてみました。

```
akiyoshi@beetle:~/chipyard/sims/verilator$ ./simulator-chipyard-MediumBoomConfig  pk  ~/gcd.riscv
This emulator compiled with JTAG Remote Bitbang client. To enable, use +jtag_rbb_enable=1.
Listening on port 43919
[UART] UART0 is here (stdin/stdout).
simulator-chipyard-MediumBoomConfig: ../fesvr/htif.h:35: T htif_t::from_target(target_endian<T>) const [with T = long unsigned int]: Assertion `endianness == memif_endianness_little || endianness == memif_endianness_big' failed.
```

やはりうまく動きません。どこが悪いんでしょうか？

**Comment by m1goh** [comment]
```
akiyoshi@beetle:~/chipyard/sims/verilator$ export RISCV=${HOME}/riscv64_github/
akiyoshi@beetle:~/chipyard/sims/verilator$ make CONFIG=RocketConfig
Running with RISCV=/home/akiyoshi/riscv64_github/
make: Nothing to be done for 'default'.
akiyoshi@beetle:~/chipyard/sims/verilator$ ls ~/
chipyard  gcd.dmp    gcd.sim.log       riscv64_github  setup.sh~  x86_test
gcd.c     gcd.riscv  llvm-myriscvx120  setup.sh        verilator
```

makeが「Nothing to be done for 'default'.」と返してきますがどこが悪いのでしょうか？

**Comment by msyksphinz-self** [comment]
MakeでやることがないということはVerilatorのシミュレーションバイナリは生成できていると思います。
`./simulator-chipyard-RocketConfig`は生成されていますでしょうか？
`./simulator-chipyard-RocketConfig pk ~/gcd.riscv`は動作しますでしょうか？

**Comment by msyksphinz-self** [comment]
```
simulator-chipyard-MediumBoomConfig: ../fesvr/htif.h:35: T htif_t::from_target(target_endian<T>) const [with T = long unsigned int]: Assertion `endianness == memif_endianness_little || endianness == memif_endianness_big' failed.
```

Docker内で同じ問題が出てきたので見ていたのですが、もしかしたらツールチェインのバージョンの違いかもしれません。Chipyardの環境でビルドできるGNUツールを使ってみていただけませんでしょうか？
具体的には、Chipyardの環境下で、
```sh
./scripts/init-submodules-no-riscv-tools.sh
./scripts/build-toolchains.sh riscv-tools --ignore-qemu
```
でRISC-Vツールチェインのダウンロードとビルドを行い（結構時間がかかります）、

```sh
source ./env.sh
source ./env-riscv-tools.sh
```

でRISCVパスおよびツールチェインんをChipyard内部のバイナリに差し替えます。

```sh
$ which riscv64-unknown-elf-gcc
${CHIPYARDディレクトリ}riscv-tools-install/bin/riscv64-unknown-elf-gcc
```

となっていればよいです。この状態でgcd.cをビルドし直してバイナリを作成して、同じようにRTLシミュレーションしてみてください。

**Comment by m1goh** [comment]
回答ありがとうございました。
ChipyardのGNUツールに切り替えてみました。環境変数の設定に余り自信がありませんがこのような感じです。

```
akiyoshi@beetle:~$ export PATH=${HOME}/chipyard/riscv-tools-install/bin:${PATH}
akiyoshi@beetle:~$ export LD_LIBRARY_PATH=${HOME}/chipyard/riscv-tools-install/lib:${LD_LIBRARY_PATH}
akiyoshi@beetle:~$ export RISCV=${HOME}/chipyard/riscv-tools-install
akiyoshi@beetle:~$ whichi riscv64_github/
bin/                 lib/                 riscv64-unknown-elf/ target/
include/             libexec/             share/
akiyoshi@beetle:~$ which ri
riched20.dll                             riscv64-unknown-linux-gnu-addr2line
riched32.dll                             riscv64-unknown-linux-gnu-ar
riscv64-unknown-elf-addr2line            riscv64-unknown-linux-gnu-as
riscv64-unknown-elf-ar                   riscv64-unknown-linux-gnu-c++
riscv64-unknown-elf-as                   riscv64-unknown-linux-gnu-c++filt
riscv64-unknown-elf-c++                  riscv64-unknown-linux-gnu-cpp
riscv64-unknown-elf-c++filt              riscv64-unknown-linux-gnu-elfedit
riscv64-unknown-elf-cpp                  riscv64-unknown-linux-gnu-g++
riscv64-unknown-elf-elfedit              riscv64-unknown-linux-gnu-gcc
riscv64-unknown-elf-g++                  riscv64-unknown-linux-gnu-gcc-9.2.0
riscv64-unknown-elf-gcc                  riscv64-unknown-linux-gnu-gcc-ar
riscv64-unknown-elf-gcc-9.2.0            riscv64-unknown-linux-gnu-gcc-nm
riscv64-unknown-elf-gcc-ar               riscv64-unknown-linux-gnu-gcc-ranlib
riscv64-unknown-elf-gcc-nm               riscv64-unknown-linux-gnu-gcov
riscv64-unknown-elf-gcc-ranlib           riscv64-unknown-linux-gnu-gcov-dump
riscv64-unknown-elf-gcov                 riscv64-unknown-linux-gnu-gcov-tool
riscv64-unknown-elf-gcov-dump            riscv64-unknown-linux-gnu-gdb
riscv64-unknown-elf-gcov-tool            riscv64-unknown-linux-gnu-gdb-add-index
riscv64-unknown-elf-gdb                  riscv64-unknown-linux-gnu-gfortran
riscv64-unknown-elf-gdb-add-index        riscv64-unknown-linux-gnu-gprof
riscv64-unknown-elf-gprof                riscv64-unknown-linux-gnu-ld
riscv64-unknown-elf-ld                   riscv64-unknown-linux-gnu-ld.bfd
riscv64-unknown-elf-ld.bfd               riscv64-unknown-linux-gnu-nm
riscv64-unknown-elf-nm                   riscv64-unknown-linux-gnu-objcopy
riscv64-unknown-elf-objcopy              riscv64-unknown-linux-gnu-objdump
riscv64-unknown-elf-objdump              riscv64-unknown-linux-gnu-ranlib
riscv64-unknown-elf-ranlib               riscv64-unknown-linux-gnu-readelf
riscv64-unknown-elf-readelf              riscv64-unknown-linux-gnu-run
riscv64-unknown-elf-run                  riscv64-unknown-linux-gnu-size
riscv64-unknown-elf-size                 riscv64-unknown-linux-gnu-strings
akiyoshi@beetle:~$ which riscv64-unknown-elf-gcc
/home/akiyoshi/chipyard/riscv-tools-install/bin/riscv64-unknown-elf-gcc
akiyoshi@beetle:~$ riscv64-unknown-elf-gcc -O2 -g ~/gcd.c -o ~/gcd.riscv
akiyoshi@beetle:~$ ls -la ~/gcd.riscv
-rwxr-xr-x 1 akiyoshi akiyoshi 145544 Aug 27 17:34 /home/akiyoshi/gcd.riscv
akiyoshi@beetle:~$ cd chipyard//sims/verilator/
akiyoshi@beetle:~/chipyard/sims/verilator$ make CONFIG=RocketConfig
Running with RISCV=/home/akiyoshi/chipyard/riscv-tools-install
make: Nothing to be done for 'default'.
akiyoshi@beetle:~/chipyard/sims/verilator$ rm
rm: missing operand
Try 'rm --help' for more information.
akiyoshi@beetle:~/chipyard/sims/verilator$ ls
Makefile  generated-src  simulator-chipyard-RocketConfig  simulator-chipyard-RocketConfig.old
akiyoshi@beetle:~/chipyard/sims/verilator$ rm simulator-chipyard-RocketConfig.old
akiyoshi@beetle:~/chipyard/sims/verilator$ mv simulator-chipyard-RocketConfig simulator-chipyard-RocketConfig.old
akiyoshi@beetle:~/chipyard/sims/verilator$ make CONFIG=RocketConfig
Running with RISCV=/home/akiyoshi/chipyard/riscv-tools-install
make VM_PARALLEL_BUILDS=1 -C /home/akiyoshi/chipyard/sims/verilator/generated-src/chipyard.TestHarness.RocketConfig/chipyard.TestHarness.RocketConfig -f VTestHarness.mk
make[1]: Entering directory '/home/akiyoshi/chipyard/sims/verilator/generated-src/chipyard.TestHarness.RocketConfig/chipyard.TestHarness.RocketConfig'
g++    SimDRAM.o SimDTM.o SimJTAG.o SimSerial.o SimUART.o emulator.o mm.o mm_dramsim2.o remote_bitbang.o testchip_tsi.o uart.o verilated.o verilated_dpi.o verilated_vpi.o VTestHarness__ALL.a   -L/home/akiyoshi/riscv64_github//lib -Wl,-rpath,/home/akiyoshi/riscv64_github//lib -L/home/akiyoshi/chipyard/sims/verilator -L/home/akiyoshi/chipyard/tools/DRAMSim2 -lfesvr -ldramsim  -pthread -lpthread -latomic -o /home/akiyoshi/chipyard/sims/verilator/simulator-chipyard-RocketConfig
make[1]: Leaving directory '/home/akiyoshi/chipyard/sims/verilator/generated-src/chipyard.TestHarness.RocketConfig/chipyard.TestHarness.RocketConfig'
akiyoshi@beetle:~/chipyard/sims/verilator$ ls
Makefile  generated-src  simulator-chipyard-RocketConfig  simulator-chipyard-RocketConfig.old
akiyoshi@beetle:~/chipyard/sims/verilator$ ./simulator-chipyard-RocketConfig pk ~/gcd.riscv
This emulator compiled with JTAG Remote Bitbang client. To enable, use +jtag_rbb_enable=1.
Listening on port 39257
[UART] UART0 is here (stdin/stdout).
simulator-chipyard-RocketConfig: ../fesvr/htif.h:35: T htif_t::from_target(target_endian<T>) const [with T = long unsigned int]: Assertion `endianness == memif_endianness_little || endianness == memif_endianness_big' failed.
akiyoshi@beetle:~/chipyard/sims/verilator$ spike pk ~/gcd.riscv
bbl loader
GCD(273, 21) = 21
GCD(411, 27117) = 3
```

Rocket-Chipでは、うまく動きません。Spikeだと動きます。どこが悪いのでしょうか？

**Comment by msyksphinz-self** [comment]
詳細ログありがとうございます。いろいろ解析して、一つ確かだと思っているのは、テスト実行用のバイナリ自体に問題はないはずです（既存の成功バイナリでも、この問題が出ました）。
`sims/verilator/generated-src/chipyard.TestHarness.RocketConfig`以下も念のため一度削除して、再ビルドしてみていただけないでしょうか？経験上こちらに`.d`ファイルなどの環境依存のファイルが残り、古い情報が消え切っていない場合があります。

**Comment by msyksphinz-self** [comment]
正式リリース前のテスト版で大変恐縮ですが、本書の環境を完全再現するためのDockerコンテナも準備中です。

https://github.com/msyksphinz-self/support_ca_llvm_book/tree/main/docker

https://hub.docker.com/repository/docker/msyksphinz/support_llvm

Dockerfile内に、Chipyardの環境構築手順を載せています。もし時間がありましたら、こちらも参照いただき、お手元の環境とどう異なるのか確認いただけるかもしれません。

https://github.com/msyksphinz-self/support_ca_llvm_book/blob/main/docker/ubuntu_2204/Dockerfile#L44

**Comment by m1goh** [comment]
回答ありがとうございます。
chipyardを削除して、ChipyardのGNUツールもビルドし直してみました。
RTLシュミレーションをしてみました。今度は、うまく動きました。
こんな感じです。

akiyoshi@beetle:~/chipyard/sims/verilator$ ./simulator-chipyard-RocketConfig pk ~/gcd.riscv
This emulator compiled with JTAG Remote Bitbang client. To enable, use +jtag_rbb_enable=1.
Listening on port 35129
[UART] UART0 is here (stdin/stdout).
bbl loader
GCD(273, 21) = 21
GCD(411, 27117) = 3
akiyoshi@beetle:~/chipyard/sims/verilator$ spike pk ~/gcd.riscv

Command 'spike' not found, did you mean:

  command 'spipe' from deb spiped (1.6.0-5)
  command 'spine' from deb cacti-spine (1.2.6-1build1)

Try: sudo apt install <deb name>

akiyoshi@beetle:~/chipyard/sims/verilator$ export PATH=${HOME}/chipyard/riscv-tools-install/bin:${PATH}
akiyoshi@beetle:~/chipyard/sims/verilator$ export LD_LIBRARY_PATH=${HOME}/chipyard/riscv-tools-install/lib:${LD_LIBRARY_PATH}
akiyoshi@beetle:~/chipyard/sims/verilator$ spike pk ~/gcd.riscv
bbl loader
GCD(273, 21) = 21
GCD(411, 27117) = 3

ありがとうございました。
