### ISSUE TITLE
LLVMのビルドについて

### ISSUE THREAD

**Issue by m1goh** [msyksphinz-self/support_ca_llvm_book#15]
本の96ページにしたがってLLVMをビルドしてみました。何度かやってみましたが同じ所でエラーになってninjaを抜けてきてしまいます。次のようになります。

akiyoshi@beetle:~/llvm-myriscv120/build$ ninja
[24/2905] Building CXX object lib/Target/AArch64/CMakeFiles/LLVMAArch64CodeGen.dir/AArch64ISelDAGToDAG.cpp.o
FAILED: lib/Target/AArch64/CMakeFiles/LLVMAArch64CodeGen.dir/AArch64ISelDAGToDAG.cpp.o
/usr/bin/c++  -DGTEST_HAS_RTTI=0 -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Ilib/Target/AArch64 -I/home/akiyoshi/llvm-myriscv120/llvm/lib/Target/AArch64 -Iinclude -I/home/akiyoshi/llvm-myriscv120/llvm/include -fPIC -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -fdiagnostics-color -g -fvisibility=hidden    -fno-exceptions -fno-rtti -std=c++14 -MD -MT lib/Target/AArch64/CMakeFiles/LLVMAArch64CodeGen.dir/AArch64ISelDAGToDAG.cpp.o -MF lib/Target/AArch64/CMakeFiles/LLVMAArch64CodeGen.dir/AArch64ISelDAGToDAG.cpp.o.d -o lib/Target/AArch64/CMakeFiles/LLVMAArch64CodeGen.dir/AArch64ISelDAGToDAG.cpp.o -c /home/akiyoshi/llvm-myriscv120/llvm/lib/Target/AArch64/AArch64ISelDAGToDAG.cpp
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
[25/2905] Building CXX object lib/Target/AArch64/MCTargetDesc/CMakeFiles/LLVMAArch64Desc.dir/AArch64TargetStreamer.cpp.
FAILED: lib/Target/AArch64/MCTargetDesc/CMakeFiles/LLVMAArch64Desc.dir/AArch64TargetStreamer.cpp.o
/usr/bin/c++  -DGTEST_HAS_RTTI=0 -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Ilib/Target/AArch64/MCTargetDesc -I/home/akiyoshi/llvm-myriscv120/llvm/lib/Target/AArch64/MCTargetDesc -I/home/akiyoshi/llvm-myriscv120/llvm/lib/Target/AArch64 -Ilib/Target/AArch64 -Iinclude -I/home/akiyoshi/llvm-myriscv120/llvm/include -I/home/akiyoshi/llvm-myriscv120/llvm/lib/Target/AArch64/MCTargetDesc/.. -Ilib/Target/AArch64/MCTargetDesc/.. -fPIC -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -fdiagnostics-color -g -fvisibility=hidden    -fno-exceptions -fno-rtti -std=c++14 -MD -MT lib/Target/AArch64/MCTargetDesc/CMakeFiles/LLVMAArch64Desc.dir/AArch64TargetStreamer.cpp.o -MF lib/Target/AArch64/MCTargetDesc/CMakeFiles/LLVMAArch64Desc.dir/AArch64TargetStreamer.cpp.o.d -o lib/Target/AArch64/MCTargetDesc/CMakeFiles/LLVMAArch64Desc.dir/AArch64TargetStreamer.cpp.o -c /home/akiyoshi/llvm-myriscv120/llvm/lib/Target/AArch64/MCTargetDesc/AArch64TargetStreamer.cpp
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
[26/2905] Building CXX object lib/Target/ARM/CMakeFiles/LLVMARMCodeGen.dir/ARMBaseInstrInfo.cpp.o
FAILED: lib/Target/ARM/CMakeFiles/LLVMARMCodeGen.dir/ARMBaseInstrInfo.cpp.o
/usr/bin/c++  -DGTEST_HAS_RTTI=0 -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Ilib/Target/ARM -I/home/akiyoshi/llvm-myriscv120/llvm/lib/Target/ARM -Iinclude -I/home/akiyoshi/llvm-myriscv120/llvm/include -fPIC -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -fdiagnostics-color -g -fvisibility=hidden    -fno-exceptions -fno-rtti -std=c++14 -MD -MT lib/Target/ARM/CMakeFiles/LLVMARMCodeGen.dir/ARMBaseInstrInfo.cpp.o -MF lib/Target/ARM/CMakeFiles/LLVMARMCodeGen.dir/ARMBaseInstrInfo.cpp.o.d -o lib/Target/ARM/CMakeFiles/LLVMARMCodeGen.dir/ARMBaseInstrInfo.cpp.o -c /home/akiyoshi/llvm-myriscv120/llvm/lib/Target/ARM/ARMBaseInstrInfo.cpp
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
[41/2905] Building CXX object lib/Target/AArch64/CMakeFiles/LLVMAArch64CodeGen.dir/AArch64TargetMachine.cpp.o
ninja: build stopped: subcommand failed.

正常にビルドを終了させたいです。どこを直せばいいのか教えていただけるとありがたいです。よろしくお願いします。

**Comment by msyksphinz-self** [comment]
ご質問ありがとうございます。このメッセージだけだと想像の域を出ないのですが、並列ビルドに対してメモリが足りず強制終了させらてれいるかもしれません。`ninja -j1`など、並列数を絞って試していただけますでしょうか？

**Comment by m1goh** [comment]
回答をありがとうございます。
ninja -j1を試してみました。

akiyoshi@beetle:~/llvm-myriscv120/build$ ninja -j1
[10/440] Linking CXX executable bin/clang-12
FAILED: bin/clang-12
: && /usr/bin/c++  -fPIC -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -fdiagnostics-color -fno-common -Woverloaded-virtual -fno-strict-aliasing -g  -Wl,--export-dynamic  -Wl,-rpath-link,/home/akiyoshi/llvm-myriscv120/build/./lib tools/clang/tools/driver/CMakeFiles/clang.dir/driver.cpp.o tools/clang/tools/driver/CMakeFiles/clang.dir/cc1_main.cpp.o tools/clang/tools/driver/CMakeFiles/clang.dir/cc1as_main.cpp.o tools/clang/tools/driver/CMakeFiles/clang.dir/cc1gen_reproducer_main.cpp.o  -o bin/clang-12  -Wl,-rpath,"\$ORIGIN/../lib"  lib/libLLVMAArch64CodeGen.a  lib/libLLVMAArch64AsmParser.a  lib/libLLVMAArch64Desc.a  lib/libLLVMAArch64Disassembler.a  lib/libLLVMAArch64Info.a  lib/libLLVMAArch64Utils.a  lib/libLLVMAMDGPUCodeGen.a  lib/libLLVMAMDGPUAsmParser.a  lib/libLLVMAMDGPUDesc.a  lib/libLLVMAMDGPUDisassembler.a  lib/libLLVMAMDGPUInfo.a  lib/libLLVMAMDGPUUtils.a  lib/libLLVMARMCodeGen.a  lib/libLLVMARMAsmParser.a  lib/libLLVMARMDesc.a  lib/libLLVMARMDisassembler.a  lib/libLLVMARMInfo.a  lib/libLLVMARMUtils.a  lib/libLLVMAVRCodeGen.a  lib/libLLVMAVRAsmParser.a  lib/libLLVMAVRDesc.a  lib/libLLVMAVRDisassembler.a  lib/libLLVMAVRInfo.a  lib/libLLVMBPFCodeGen.a  lib/libLLVMBPFAsmParser.a  lib/libLLVMBPFDesc.a  lib/libLLVMBPFDisassembler.a  lib/libLLVMBPFInfo.a  lib/libLLVMHexagonCodeGen.a  lib/libLLVMHexagonAsmParser.a  lib/libLLVMHexagonDesc.a  lib/libLLVMHexagonDisassembler.a  lib/libLLVMHexagonInfo.a  lib/libLLVMLanaiCodeGen.a  lib/libLLVMLanaiAsmParser.a  lib/libLLVMLanaiDesc.a  lib/libLLVMLanaiDisassembler.a  lib/libLLVMLanaiInfo.a  lib/libLLVMMipsCodeGen.a  lib/libLLVMMipsAsmParser.a  lib/libLLVMMipsDesc.a  lib/libLLVMMipsDisassembler.a  lib/libLLVMMipsInfo.a  lib/libLLVMMSP430CodeGen.a  lib/libLLVMMSP430AsmParser.a  lib/libLLVMMSP430Desc.a  lib/libLLVMMSP430Disassembler.a  lib/libLLVMMSP430Info.a  lib/libLLVMNVPTXCodeGen.a  lib/libLLVMNVPTXDesc.a  lib/libLLVMNVPTXInfo.a  lib/libLLVMPowerPCCodeGen.a  lib/libLLVMPowerPCAsmParser.a  lib/libLLVMPowerPCDesc.a  lib/libLLVMPowerPCDisassembler.a  lib/libLLVMPowerPCInfo.a  lib/libLLVMRISCVCodeGen.a  lib/libLLVMRISCVAsmParser.a  lib/libLLVMRISCVDesc.a  lib/libLLVMRISCVDisassembler.a  lib/libLLVMRISCVInfo.a  lib/libLLVMSparcCodeGen.a  lib/libLLVMSparcAsmParser.a  lib/libLLVMSparcDesc.a  lib/libLLVMSparcDisassembler.a  lib/libLLVMSparcInfo.a  lib/libLLVMSystemZCodeGen.a  lib/libLLVMSystemZAsmParser.a  lib/libLLVMSystemZDesc.a  lib/libLLVMSystemZDisassembler.a  lib/libLLVMSystemZInfo.a  lib/libLLVMWebAssemblyCodeGen.a  lib/libLLVMWebAssemblyAsmParser.a  lib/libLLVMWebAssemblyDesc.a  lib/libLLVMWebAssemblyDisassembler.a  lib/libLLVMWebAssemblyInfo.a  lib/libLLVMX86CodeGen.a  lib/libLLVMX86AsmParser.a  lib/libLLVMX86Desc.a  lib/libLLVMX86Disassembler.a  lib/libLLVMX86Info.a  lib/libLLVMXCoreCodeGen.a  lib/libLLVMXCoreDesc.a  lib/libLLVMXCoreDisassembler.a  lib/libLLVMXCoreInfo.a  lib/libLLVMAnalysis.a  lib/libLLVMCodeGen.a  lib/libLLVMCore.a  lib/libLLVMipo.a  lib/libLLVMAggressiveInstCombine.a  lib/libLLVMInstCombine.a  lib/libLLVMInstrumentation.a  lib/libLLVMMC.a  lib/libLLVMMCParser.a  lib/libLLVMObjCARCOpts.a  lib/libLLVMOption.a  lib/libLLVMScalarOpts.a  lib/libLLVMSupport.a  lib/libLLVMTransformUtils.a  lib/libLLVMVectorize.a  -lpthread  lib/libclangBasic.a  lib/libclangCodeGen.a  lib/libclangDriver.a  lib/libclangFrontend.a  lib/libclangFrontendTool.a  lib/libclangSerialization.a  lib/libLLVMAArch64Desc.a  lib/libLLVMAArch64Info.a  lib/libLLVMAArch64Utils.a  lib/libLLVMMIRParser.a  lib/libLLVMAMDGPUDesc.a  lib/libLLVMAMDGPUInfo.a  lib/libLLVMAMDGPUUtils.a  lib/libLLVMARMDesc.a  lib/libLLVMARMInfo.a  lib/libLLVMARMUtils.a  lib/libLLVMHexagonDesc.a  lib/libLLVMHexagonInfo.a  lib/libLLVMLanaiDesc.a  lib/libLLVMLanaiInfo.a  lib/libLLVMSystemZDesc.a  lib/libLLVMSystemZInfo.a  lib/libLLVMWebAssemblyDesc.a  lib/libLLVMWebAssemblyInfo.a  lib/libLLVMGlobalISel.a  lib/libLLVMCFGuard.a  lib/libLLVMAsmPrinter.a  lib/libLLVMDebugInfoDWARF.a  lib/libLLVMSelectionDAG.a  lib/libLLVMMCDisassembler.a  lib/libclangCodeGen.a  lib/libLLVMCoverage.a  lib/libLLVMLTO.a  lib/libLLVMCodeGen.a  lib/libLLVMPasses.a  lib/libLLVMObjCARCOpts.a  lib/libLLVMTarget.a  lib/libLLVMCoroutines.a  lib/libLLVMipo.a  lib/libLLVMInstrumentation.a  lib/libLLVMVectorize.a  lib/libLLVMIRReader.a  lib/libLLVMAsmParser.a  lib/libLLVMScalarOpts.a  lib/libLLVMAggressiveInstCombine.a  lib/libLLVMInstCombine.a  lib/libLLVMHelloNew.a  lib/libLLVMBitWriter.a  lib/libLLVMLinker.a  lib/libLLVMExtensions.a  lib/libclangRewriteFrontend.a  lib/libclangARCMigrate.a  lib/libclangStaticAnalyzerFrontend.a  lib/libclangStaticAnalyzerCheckers.a  lib/libclangStaticAnalyzerCore.a  lib/libclangCrossTU.a  lib/libclangIndex.a  lib/libclangFrontend.a  lib/libclangDriver.a  lib/libLLVMOption.a  lib/libclangParse.a  lib/libclangSerialization.a  lib/libclangSema.a  lib/libclangAnalysis.a  lib/libclangASTMatchers.a  lib/libclangEdit.a  lib/libclangAST.a  lib/libLLVMFrontendOpenMP.a  lib/libLLVMTransformUtils.a  lib/libLLVMAnalysis.a  lib/libLLVMProfileData.a  lib/libLLVMObject.a  lib/libLLVMMCParser.a  lib/libLLVMBitReader.a  lib/libLLVMTextAPI.a  lib/libclangFormat.a  lib/libclangToolingInclusions.a  lib/libclangToolingCore.a  lib/libclangRewrite.a  lib/libclangLex.a  lib/libclangBasic.a  lib/libLLVMCore.a  lib/libLLVMRemarks.a  lib/libLLVMBitstreamReader.a  lib/libLLVMMC.a  lib/libLLVMBinaryFormat.a  lib/libLLVMDebugInfoCodeView.a  lib/libLLVMDebugInfoMSF.a  lib/libLLVMSupport.a  -lrt  -ldl  -lpthread  -lm  /usr/lib/x86_64-linux-gnu/libz.so  lib/libLLVMDemangle.a && :
collect2: fatal error: ld terminated with signal 9 [Killed]
compilation terminated.
ninja: build stopped: subcommand failed.

ninja -j1でも起こりました。どこが悪いのでしょう？

**Comment by msyksphinz-self** [comment]
最初は残りビルド数が2905だったのが、440まで減ってきましたね。結構ビルドが進んだ後、最終的に落ちた感じでしょうか。やはりメモリ不足で落ちているのかと予想しますが、使用可能なメモリはどれくらいでしょうか？

確実にビルドできることを確認したいので、とりあえずメモリを節約するためにDebugオプションではなくReleaseオプションでビルドしてうまくいくか、確認してみるといいかもしれません。
最初の`cmake`のオプションで`-DCMAKE_BUILD_TYPE="Debug"` としているものを`-DCMAKE_BUILD_TYPE="Release"`に変更し、`ninja -j1`とするとどうなりますでしょうか。時間はかかりますが少ないメモリ量で進むはずです。

**Comment by m1goh** [comment]
回答をありがとうございます。
ビルド時の利用可能なメモリはタスクマネージャを見ていたのですが確認してみませんでした。今の状態では6.5GBです。

Relaseオプションでのビルド最後まで完了しました。
[4070/4070] Copying llvm-locstats into /home/akiyoshi/llvm-myriscv120/build/./bin
akiyoshi@beetle:~/llvm-myriscv120/build$ cd bin
akiyoshi@beetle:~/llvm-myriscv120/build/bin$ ls -l
total 2399584
-rwxr-xr-x 1 akiyoshi akiyoshi    794368 Aug 16 21:15 FileCheck
-rwxr-xr-x 1 akiyoshi akiyoshi    634224 Aug 16 22:18 apinotes-test
-rwxr-xr-x 1 akiyoshi akiyoshi  43763872 Aug 16 22:20 arcmt-test
-rwxr-xr-x 1 akiyoshi akiyoshi 116641280 Aug 16 22:22 bugpoint
-rwxr-xr-x 1 akiyoshi akiyoshi     17608 Aug 16 22:21 c-arcmt-test
-rwxr-xr-x 1 akiyoshi akiyoshi  42719152 Aug 16 22:21 c-index-test
lrwxrwxrwx 1 akiyoshi akiyoshi         8 Aug 16 22:19 clang -> clang-12
lrwxrwxrwx 1 akiyoshi akiyoshi         8 Aug 16 22:19 clang++ -> clang-12
-rwxr-xr-x 1 akiyoshi akiyoshi 187856864 Aug 16 22:19 clang-12
-rwxr-xr-x 1 akiyoshi akiyoshi 143096608 Aug 16 22:20 clang-check
lrwxrwxrwx 1 akiyoshi akiyoshi         8 Aug 16 22:19 clang-cl -> clang-12
lrwxrwxrwx 1 akiyoshi akiyoshi         8 Aug 16 22:19 clang-cpp -> clang-12
-rwxr-xr-x 1 akiyoshi akiyoshi  41429624 Aug 16 22:18 clang-diff
-rwxr-xr-x 1 akiyoshi akiyoshi  40764848 Aug 16 22:20 clang-extdef-mapping
-rwxr-xr-x 1 akiyoshi akiyoshi   2864384 Aug 16 22:18 clang-format
-rwxr-xr-x 1 akiyoshi akiyoshi  52343480 Aug 16 22:18 clang-import-test
-rwxr-xr-x 1 akiyoshi akiyoshi   5590760 Aug 16 22:18 clang-offload-bundler
-rwxr-xr-x 1 akiyoshi akiyoshi   3857816 Aug 16 22:18 clang-offload-wrapper
-rwxr-xr-x 1 akiyoshi akiyoshi  43569640 Aug 16 22:19 clang-refactor
-rwxr-xr-x 1 akiyoshi akiyoshi  41918496 Aug 16 22:19 clang-rename
-rwxr-xr-x 1 akiyoshi akiyoshi  40963344 Aug 16 22:19 clang-scan-deps
-rwxr-xr-x 1 akiyoshi akiyoshi   2150320 Aug 16 21:17 clang-tblgen
-rwxr-xr-x 1 akiyoshi akiyoshi     16864 Aug 16 21:15 count
-rwxr-xr-x 1 akiyoshi akiyoshi  11993304 Aug 16 22:18 diagtool
-rwxr-xr-x 1 akiyoshi akiyoshi  88742272 Aug 16 22:22 dsymutil
-rwxr-xr-x 1 akiyoshi akiyoshi      9980 Aug 16 15:56 hmaptool
-rwxr-xr-x 1 akiyoshi akiyoshi 116382832 Aug 16 22:22 llc
-rwxr-xr-x 1 akiyoshi akiyoshi  47792592 Aug 16 22:22 lli
-rwxr-xr-x 1 akiyoshi akiyoshi    563472 Aug 16 22:22 lli-child-target
-rwxr-xr-x 1 akiyoshi akiyoshi     28160 Aug 16 21:15 llvm-PerfectShuffle
lrwxrwxrwx 1 akiyoshi akiyoshi        15 Aug 16 22:31 llvm-addr2line -> llvm-symbolizer
-rwxr-xr-x 1 akiyoshi akiyoshi  31408800 Aug 16 21:16 llvm-ar
-rwxr-xr-x 1 akiyoshi akiyoshi   5260936 Aug 16 22:22 llvm-as
-rwxr-xr-x 1 akiyoshi akiyoshi    551168 Aug 16 22:22 llvm-bcanalyzer
lrwxrwxrwx 1 akiyoshi akiyoshi        12 Aug 16 22:27 llvm-bitcode-strip -> llvm-objcopy
-rwxr-xr-x 1 akiyoshi akiyoshi  87848984 Aug 16 22:23 llvm-c-test
-rwxr-xr-x 1 akiyoshi akiyoshi   4778968 Aug 16 22:23 llvm-cat
-rwxr-xr-x 1 akiyoshi akiyoshi  36842656 Aug 16 22:23 llvm-cfi-verify
-rwxr-xr-x 1 akiyoshi akiyoshi    551608 Aug 16 21:16 llvm-config
-rwxr-xr-x 1 akiyoshi akiyoshi   6742872 Aug 16 22:23 llvm-cov
-rwxr-xr-x 1 akiyoshi akiyoshi   5574120 Aug 16 22:23 llvm-cvtres
-rwxr-xr-x 1 akiyoshi akiyoshi   5624240 Aug 16 22:23 llvm-cxxdump
-rwxr-xr-x 1 akiyoshi akiyoshi    615728 Aug 16 22:23 llvm-cxxfilt
-rwxr-xr-x 1 akiyoshi akiyoshi    744392 Aug 16 22:23 llvm-cxxmap
-rwxr-xr-x 1 akiyoshi akiyoshi   4408616 Aug 16 22:23 llvm-diff
-rwxr-xr-x 1 akiyoshi akiyoshi   4048296 Aug 16 22:23 llvm-dis
lrwxrwxrwx 1 akiyoshi akiyoshi         7 Aug 16 21:16 llvm-dlltool -> llvm-ar
-rwxr-xr-x 1 akiyoshi akiyoshi  26237056 Aug 16 22:24 llvm-dwarfdump
-rwxr-xr-x 1 akiyoshi akiyoshi  87162080 Aug 16 22:24 llvm-dwp
-rwxr-xr-x 1 akiyoshi akiyoshi   5734656 Aug 16 22:24 llvm-elfabi
-rwxr-xr-x 1 akiyoshi akiyoshi  38503472 Aug 16 22:25 llvm-exegesis
-rwxr-xr-x 1 akiyoshi akiyoshi   8647392 Aug 16 22:25 llvm-extract
-rwxr-xr-x 1 akiyoshi akiyoshi  80267928 Aug 16 22:25 llvm-gsymutil
-rwxr-xr-x 1 akiyoshi akiyoshi   2946248 Aug 16 22:25 llvm-ifs
lrwxrwxrwx 1 akiyoshi akiyoshi        12 Aug 16 22:27 llvm-install-name-tool -> llvm-objcopy
-rwxr-xr-x 1 akiyoshi akiyoshi  92109024 Aug 16 22:25 llvm-isel-fuzzer
-rwxr-xr-x 1 akiyoshi akiyoshi    690416 Aug 16 22:25 llvm-itanium-demangle-fuzzer
-rwxr-xr-x 1 akiyoshi akiyoshi  42170808 Aug 16 22:25 llvm-jitlink
-rwxr-xr-x 1 akiyoshi akiyoshi   1617272 Aug 16 22:25 llvm-jitlink-executor
lrwxrwxrwx 1 akiyoshi akiyoshi         7 Aug 16 21:16 llvm-lib -> llvm-ar
-rwxr-xr-x 1 akiyoshi akiyoshi   5846176 Aug 16 22:26 llvm-libtool-darwin
-rwxr-xr-x 1 akiyoshi akiyoshi   6157040 Aug 16 22:26 llvm-link
-rwxr-xr-x 1 akiyoshi akiyoshi   5795232 Aug 16 22:26 llvm-lipo
-rwxr-xr-x 1 akiyoshi akiyoshi      1602 Aug 16 13:47 llvm-lit
-rwxr-xr-x 1 akiyoshi akiyoshi     14008 Aug 16 22:33 llvm-locstats
-rwxr-xr-x 1 akiyoshi akiyoshi 103674192 Aug 16 21:16 llvm-lto
-rwxr-xr-x 1 akiyoshi akiyoshi 115374904 Aug 16 22:26 llvm-lto2
-rwxr-xr-x 1 akiyoshi akiyoshi  31098368 Aug 16 22:26 llvm-mc
-rwxr-xr-x 1 akiyoshi akiyoshi  27624504 Aug 16 22:26 llvm-mca
-rwxr-xr-x 1 akiyoshi akiyoshi    640896 Aug 16 22:26 llvm-microsoft-demangle-fuzzer
-rwxr-xr-x 1 akiyoshi akiyoshi  30991088 Aug 16 22:26 llvm-ml
-rwxr-xr-x 1 akiyoshi akiyoshi   5028936 Aug 16 22:26 llvm-modextract
-rwxr-xr-x 1 akiyoshi akiyoshi    406280 Aug 16 22:26 llvm-mt
-rwxr-xr-x 1 akiyoshi akiyoshi  31879512 Aug 16 22:26 llvm-nm
-rwxr-xr-x 1 akiyoshi akiyoshi   6682016 Aug 16 22:27 llvm-objcopy
-rwxr-xr-x 1 akiyoshi akiyoshi  30766024 Aug 16 22:28 llvm-objdump
-rwxr-xr-x 1 akiyoshi akiyoshi  99319800 Aug 16 22:28 llvm-opt-fuzzer
-rwxr-xr-x 1 akiyoshi akiyoshi    884216 Aug 16 22:27 llvm-opt-report
-rwxr-xr-x 1 akiyoshi akiyoshi   8911792 Aug 16 22:28 llvm-pdbutil
-rwxr-xr-x 1 akiyoshi akiyoshi   3308520 Aug 16 21:13 llvm-profdata
-rwxr-xr-x 1 akiyoshi akiyoshi  31371448 Aug 16 22:29 llvm-profgen
lrwxrwxrwx 1 akiyoshi akiyoshi         7 Aug 16 21:16 llvm-ranlib -> llvm-ar
-rwxr-xr-x 1 akiyoshi akiyoshi    615144 Aug 16 22:29 llvm-rc
lrwxrwxrwx 1 akiyoshi akiyoshi        12 Aug 16 22:30 llvm-readelf -> llvm-readobj
-rwxr-xr-x 1 akiyoshi akiyoshi   9415848 Aug 16 22:30 llvm-readobj
-rwxr-xr-x 1 akiyoshi akiyoshi   4863464 Aug 16 22:30 llvm-reduce
-rwxr-xr-x 1 akiyoshi akiyoshi  26253872 Aug 16 22:30 llvm-rtdyld
-rwxr-xr-x 1 akiyoshi akiyoshi   5617632 Aug 16 22:30 llvm-size
-rwxr-xr-x 1 akiyoshi akiyoshi    545616 Aug 16 22:30 llvm-special-case-list-fuzzer
-rwxr-xr-x 1 akiyoshi akiyoshi   5732288 Aug 16 22:30 llvm-split
-rwxr-xr-x 1 akiyoshi akiyoshi   3314888 Aug 16 22:30 llvm-stress
-rwxr-xr-x 1 akiyoshi akiyoshi    447136 Aug 16 22:31 llvm-strings
lrwxrwxrwx 1 akiyoshi akiyoshi        12 Aug 16 22:27 llvm-strip -> llvm-objcopy
-rwxr-xr-x 1 akiyoshi akiyoshi   7847424 Aug 16 22:31 llvm-symbolizer
-rwxr-xr-x 1 akiyoshi akiyoshi   4556480 Aug 16 19:15 llvm-tblgen
-rwxr-xr-x 1 akiyoshi akiyoshi    553944 Aug 16 22:31 llvm-undname
-rwxr-xr-x 1 akiyoshi akiyoshi   8458744 Aug 16 22:31 llvm-xray
-rwxr-xr-x 1 akiyoshi akiyoshi    542000 Aug 16 22:31 llvm-yaml-numeric-parser-fuzzer
-rwxr-xr-x 1 akiyoshi akiyoshi    631000 Aug 16 22:31 llvm-yaml-parser-fuzzer
-rwxr-xr-x 1 akiyoshi akiyoshi    253200 Aug 16 21:15 not
-rwxr-xr-x 1 akiyoshi akiyoshi   8838704 Aug 16 22:32 obj2yaml
-rwxr-xr-x 1 akiyoshi akiyoshi 116748848 Aug 16 22:32 opt
-rwxr-xr-x 1 akiyoshi akiyoshi  31140768 Aug 16 22:32 sancov
-rwxr-xr-x 1 akiyoshi akiyoshi   7718040 Aug 16 22:32 sanstats
-rwxr-xr-x 1 akiyoshi akiyoshi     58072 Aug 16 15:56 scan-build
-rwxr-xr-x 1 akiyoshi akiyoshi      4702 Aug 16 15:56 scan-view
-rwxr-xr-x 1 akiyoshi akiyoshi    384504 Aug 16 21:18 split-file
-rwxr-xr-x 1 akiyoshi akiyoshi   5647336 Aug 16 22:32 verify-uselistorder
-rwxr-xr-x 1 akiyoshi akiyoshi    534928 Aug 16 21:15 yaml-bench
-rwxr-xr-x 1 akiyoshi akiyoshi   2830096 Aug 16 22:32 yaml2obj
akiyoshi@beetle:~/llvm-myriscv120/build/bin$ ./llc
^Z
[1]+  Stopped                 ./llc
akiyoshi@beetle:~/llvm-myriscv120/build/bin$ ./llc --version
LLVM (http://llvm.org/):
  LLVM version 12.0.1
  Optimized build with assertions.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: znver2

  Registered Targets:
    aarch64    - AArch64 (little endian)
    aarch64_32 - AArch64 (little endian ILP32)
    aarch64_be - AArch64 (big endian)
    amdgcn     - AMD GCN GPUs
    arm        - ARM
    arm64      - ARM64 (little endian)
    arm64_32   - ARM64 (little endian ILP32)
    armeb      - ARM (big endian)
    avr        - Atmel AVR Microcontroller
    bpf        - BPF (host endian)
    bpfeb      - BPF (big endian)
    bpfel      - BPF (little endian)
    hexagon    - Hexagon
    lanai      - Lanai
    mips       - MIPS (32-bit big endian)
    mips64     - MIPS (64-bit big endian)
    mips64el   - MIPS (64-bit little endian)
    mipsel     - MIPS (32-bit little endian)
    msp430     - MSP430 [experimental]
    nvptx      - NVIDIA PTX 32-bit
    nvptx64    - NVIDIA PTX 64-bit
    ppc32      - PowerPC 32
    ppc32le    - PowerPC 32 LE
    ppc64      - PowerPC 64
    ppc64le    - PowerPC 64 LE
    r600       - AMD GPUs HD2XXX-HD6XXX
    riscv32    - 32-bit RISC-V
    riscv64    - 64-bit RISC-V
    sparc      - Sparc
    sparcel    - Sparc LE
    sparcv9    - Sparc V9
    systemz    - SystemZ
    thumb      - Thumb
    thumbeb    - Thumb (big endian)
    wasm32     - WebAssembly 32-bit
    wasm64     - WebAssembly 64-bit
    x86        - 32-bit X86: Pentium-Pro and above
    x86-64     - 64-bit X86: EM64T and AMD64
    xcore      - XCore
