### ISSUE TITLE
P147のデータレイアウトの指定について

### ISSUE THREAD

**Issue by dum-601** [msyksphinz-self/support_ca_llvm_book#17]
P147では、データアラインメントの指定が ```iA:B``` の形式で行われると記載されています。一方で、同じくP147の ```MYRISCVXTargetMachine.cpp``` では、8ビットと16ビットのデータアラインメントの指定が、```i8:8:32``` や ```i16:16:32``` といった形式で行われています。 この場合、```:```で区切られた3つ目の数値がアラインメントを表すと思うのですが、2つ目の数値は何を表すのでしょうか？ また64ビットのみ ```iA:B``` の形式である意図は何でしょうか？

**Comment by msyksphinz-self** [comment]
説明があいまいになってしまっており申し訳ありません。

`iA:B:C`という表記の場合、サイズAのデータ型をサイズBにアライメントするようにABIが定義されている、しかしサイズCにアライメントされることが好まれる(性能面において)ということになります。
ソースコード中の`i64`にのみ2番目の指定が抜けていることに本質的な意味はありません。確認が不足しており申し訳ありません。

詳細につきましては、LLVMの以下のドキュメントを参照ください(自分もなんだったっけ、と思い検索してしまいました...)

https://llvm.org/docs/LangRef.html#data-layout

**Comment by matsuoka-601** [comment]
なるほど、納得しました。
ご対応ありがとうございます。

**Comment by dum-601** [comment]
なるほど、納得しました。
ご対応ありがとうございます。
