### ISSUE TITLE
誤記報告：P71 riscv-toolsをインストールする

### ISSUE THREAD

**Issue by komainu8** [msyksphinz-self/support_ca_llvm_book#18]
大したことではないのですが、P71の以下の記載に誤記があったのでご報告いたします。

「すべてのビルドが完了たら、...」となっていますが、「すべてのビルドが完了したら、...」が正しいと思います。
（誤）完了たら
（正）完了したら

正誤表には記載がなさそうだったので、ご報告いたしました。既出の問題でしたらすみません。
書籍の版数は初版です。

**Comment by msyksphinz-self** [comment]
ありがとうございます。ご指摘の通りです。

正誤表に追加しました。

**Comment by komainu8** [comment]
ご対応ありがとうございます！
