### ISSUE TITLE
誤記報告

### ISSUE THREAD

**Issue by kiszk** [msyksphinz-self/support_ca_llvm_book#19]
ようやく一通り読むことができました。些細ですが気がついた点を。

- P64. ２段落目
    - 誤: Machine Execption Program Counter
    - 正: Machine Exception Program Counter

- P75. `0x101de`
    - 誤: `MV a5, a1`
    - 正: `MV a0, a5`

- P91. LLVM IR
    - 誤: `@add1`
    - 正: `@add`

- P127. 3段落目
    - 誤: のに与えている
    - 正: に与えている

- P141. `MYRISCVXCallingConv.td`
    - 誤: Calee Saved
    - 正: Callee Saved

- P152. `MYRISCVXCallingConv.td`
    - 誤: Calee Saved
    - 正: Callee Saved

- P185. ページ上
    - 誤: `LowerRetrun()`
    - 正: `LowerReturn()`

- P235. 4段落目
    - 誤: MahineInstr
    - 正: MachineInstr

- P260. 論理和命令
    - 誤: `ORI rd, rd2, imm`
    - 正: `ORI rd, rd1, imm`

- P263. 最終段落
    - 誤: だけだ異なります
    - 正: だけが異なります

- P265. 3段落目
    - 誤: 作業としてはの
    - 正: 作業としては

- P287. 2段落目
    - 誤: rotate_lef()
    - 正: rotate_left()

- P336. ２つ目のプログラム例
    - 誤: 20番目
    - 正: 10番目
    - 誤: `[20]`
    - 正: `[10]`

- P353. switch文
    - 誤: `/* default 選択文`
    - 正: `/* default 選択文 */`

- P358. 1つ目のアセンブリ表現
    - 誤: `EXp1 == x0を`
    - 正: `Cond == x0を`

- P358. 図44
    - 誤: func_calee
    - 正: func_callee

- P393. 1段落目
    - 誤: TargetLowerig::LowerCall()
    - 正: TargetLowering::LowerCall()

- P404. 
    - 誤: `// loaImmediate()を呼び出して`
    - 正: `// loadImmediate()を呼び出して`
    - 誤: 完了れば
    - 正: 完了すれば

- P421. 表8
    - 誤: BOOm
    - 正: BOOM

- P427. 図3
    - 誤: ELP Header
    - 正: ELF Header

- P478. 2段落目
    - 誤: まずはMYRISCVXAsmparser::parseRegister()を
    - 正: まずはMYRISCVXAsmParser::parseRegister()を

- P480. 2段落目
    - 誤: ParseImmediate()
    - 正: parseImmediate()
    - 誤: ParseRegister()
    - 正: parseRegister()

- P481. 3段落目
    - 誤: ParseMemOperand()
    - 正: parseMemOperand()
    - 誤: ParseImmediate()
    - 正: parseImmediate()

- P488. `MYRISCVXAsmParser.cpp`
    - 誤: `// -2048 から 2048までの`
    - 正: `// -2048 から 2047までの`

- P489. 2段落目
    - 誤: 2028の場合
    - 正: 2048の場合

- P489. 2段落目
    - 誤: 見つけると、、
    - 正: 見つけると、

- P500. 1段落目
    - 誤: 解放
    - 正: 解法

- P501. 1段落目
    - 誤: マスが０でない
    - 正: マスの値が０である

**Comment by msyksphinz-self** [comment]
たくさんの指摘ありがとうございます。そして出版前の確認が足りておらず申し訳ありません。
確認後正誤表に追記させていただきました (正誤表が大きくなってきたので別ページに分離しました)

https://github.com/msyksphinz-self/support_ca_llvm_book/blob/main/errata.md

**Comment by kiszk** [comment]
ご対応ありがとうございます。
