### ISSUE TITLE
READMEの "LLVMビルド時の推奨オプション" について

### ISSUE THREAD

**Issue by t-msn** [msyksphinz-self/support_ca_llvm_book#2]
(issueというよりもコメントに近いのですが)
READMEの "LLVMビルド時の推奨オプション" の項ではLLVMのビルド時に-DEFAULT_SYSROOTオプションをつける事が説明されています。
この場合、ホストがx86ならばビルドしたclangでx86をコンパイルする際(p.99)は-sysroot=/を付けなければ正しくx86のincludeファイルが読み込まれずにエラーになってしまうと思います。このためこの点について注意書きがあった方が親切ではないかと思いました。
(x86 fedora 36で実行しましたので、ubuntuとの環境の違いでしたらすみません)

**Comment by msyksphinz-self** [comment]
ご指摘ありがとうございます。READMEのビルド時についてコメントを追記しました。

**Comment by t-msn** [comment]
ありがとうございます。closeいたします。
