### ISSUE TITLE
誤記報告 : P201~202 の定数について

### ISSUE THREAD

**Issue by dum-601** [msyksphinz-self/support_ca_llvm_book#20]
P201~202 にかけて用いられている定数の例に関して、2つ誤記を報告します。
- 図16で、```0x01234def``` と ```0x01234567``` が混在しています。
- P201~202 の文中で用いられている定数の例は ```0x12345def``` ですが、図17では ```0x01234def``` が用いられています。

**Comment by msyksphinz-self** [comment]
ありがとうございます。ご指摘の通りです。正誤表に追記しました。

**Comment by dum-601** [comment]
ご対応ありがとうございます。
