### ISSUE TITLE
Dockerイメージubuntu_1804_onlyenv が起動できない

### ISSUE THREAD

**Issue by xyzpda** [msyksphinz-self/support_ca_llvm_book#24]
https://github.com/msyksphinz-self/support_ca_llvm_book/blob/main/docker/ubuntu_1804_onlyenv/README.md

上記の手順を参考にしながら Dcoker コンテナを起動しようとしましたが、
./run.sh を実行すると以下の内容が表示され起動できません。

```
$ ./run.sh 
---------------------------------
 Downloading LLVM repository ...
---------------------------------
---------------------------------
 Running Docker ...
---------------------------------
[2022-09-09T04:01:27.933244900Z][docker-credential-desktop][W] Windows version might not be up-to-date: The system cannot find the file specified.
ubuntu_1804_onlyenv: Pulling from msyksphinz/support_llvm
Digest: sha256:8724e1654007697df2794284acb35d9fd7598ab41f72852f3784eb64acef0c2e
Status: Image is up to date for msyksphinz/support_llvm:ubuntu_1804_onlyenv
docker.io/msyksphinz/support_llvm:ubuntu_1804_onlyenv
fixuid: fixuid should only ever be used on development systems. DO NOT USE IN PRODUCTION
fixuid: runtime UID '1000' already matches container user 'llvm-user' UID
fixuid: runtime GID '1000' already matches container group 'llvm-user' GID
```

Windows 10 で Docker Desktop 4.12.0 (85629) を利用しております。

お手数ですが対処法などわかりましたら教えていただけると幸いです。

**Comment by msyksphinz-self** [comment]
このあとエラーメッセージはどのように表示されますでしょうか？
私の環境ではこの後問題なくDocker内にログインできています。

```
fixuid: fixuid should only ever be used on development systems. DO NOT USE IN PRODUCTION
fixuid: runtime UID '1000' already matches container user 'llvm-user' UID
fixuid: runtime GID '1000' already matches container group 'llvm-user' GID
llvm-user@d343c3deb7c8:/llvm_book$   # <-- Docker環境にログインできている
```

1. `make_env.sh`が正しくダウンロードできているかご確認ください。`run.sh`実行前に一度実行してください。

```sh
#!/bin/sh

# referred by https://qiita.com/takumiabe/items/fee2e76e3a39fd853589

touch .env
echo "UID=$(id -u $USER)" >> .env
echo "GID=$(id -g $USER)" >> .env
echo "UNAME=$USER" >> .env
```

2. `.env`が生成されているか、確認してください。私の環境では、以下のようになります。

```
UID=1000
GID=1000
UNAME=msyksphinz
UID=1000
GID=1000
UNAME=msyksphinz
```

これは、Docker内で`root`で実行してしまうと、外部と共有されるファイルがrootで更新されてしまい、ホストから削除できなくなってしまうのを防ぐために、Docker環境をホストと同じユーザモードで動かすための対策です。
これらが正しく設定できているかをご確認ください。

**Comment by hirooih** [comment]
Ubuntu 上で ubuntu_2204_onlyenv を install して問題なく動作しました。

ここ数週間少しずつ環境を立ち上げようとしていたのですが、未経験の docker に挑戦してみました。
恐ろしく簡単に環境を手に入れることができ、動作も軽快で、早く試せばよかったと思っています。

[llvm-myriscvx-tests](https://github.com/msyksphinz-self/llvm-myriscvx-tests) も同じ directory に clone して、 `run.sh` の最後の行を

```sh
docker run --rm \
	-v ${PWD}/llvm-project:/llvm_book/llvm-project/ \
	-v ${PWD}/llvm-myriscvx-tests:/llvm_book/llvm-myriscvx-tests/ \
	-it msyksphinz/support_llvm:ubuntu_2204_onlyenv "/bin/bash"
```

とすることで、各種 sample program を `make` とするだけで、試すことができるようになりました。

Dockerのことをネットで調べたのですが、言葉がよくわからず苦労しました。同様の方の参考になればと思い、メモを共有します。

***

- 職場での展開も考慮して (条件付きで) 有償のDocker Desktopではなく、Docker Engine を https://docs.docker.com/engine/install/ubuntu/ に従って install
- 毎回 sudo しなくてよいように https://docs.docker.com/engine/install/linux-postinstall/ に従って `sudo usermod -aG docker $USER` を実行。(その前に書かれている `groupadd` は不要だったはず。)
  - logoutすれば設定が反映される、と書かれているが、Ubuntu ではrebootが必要であった。https://askubuntu.com/questions/69221/adding-user-to-a-group-why-had-to-reboot
- https://docs.docker.com/get-started/ に沿って tutorialを一通り実習したが、必ずしも必要ではなかった。ただし上記の volumeの追加ができたので、無駄ではなかった。
- https://github.com/msyksphinz-self/support_ca_llvm_book/blob/main/docker/README.md の通りにするだけ。
- VS codeを起動して、内蔵terminalで `./run.sh`

素晴らしい環境をありがとうございます。

**Comment by xyzpda** [comment]
ご回答いただきありがとうございます、また、返信が大変遅くなり申し訳ございません。

> このあとエラーメッセージはどのように表示されますでしょうか？ 私の環境ではこの後問題なくDocker内にログインできています。

このあと、bash が見つからないというエラーが発生します。ただ、環境の問題かと思い、ここは記載しておりませんでした。

`fixuid: exec: "C:/Program Files/Git/usr/bin/bash.exe": stat C:/Program Files/Git/usr/bin/bash.exe: no such file or directory`

`run.sh`を実行時のすべての内容は以下となります。

```
$ ./run.sh 
---------------------------------
 Downloading LLVM repository ...
---------------------------------
---------------------------------
 Running Docker ...
---------------------------------
[2022-09-15T07:56:46.263153900Z][docker-credential-desktop][W] Windows version might not be up-to-date: The system cannot find the file specified.
ubuntu_1804_onlyenv: Pulling from msyksphinz/support_llvm
Digest: sha256:8724e1654007697df2794284acb35d9fd7598ab41f72852f3784eb64acef0c2e
Status: Image is up to date for msyksphinz/support_llvm:ubuntu_1804_onlyenv
docker.io/msyksphinz/support_llvm:ubuntu_1804_onlyenv
fixuid: fixuid should only ever be used on development systems. DO NOT USE IN PRODUCTION
fixuid: runtime UID '1000' already matches container user 'llvm-user' UID
fixuid: runtime GID '1000' already matches container group 'llvm-user' GID
fixuid: exec: "C:/Program Files/Git/usr/bin/bash.exe": stat C:/Program Files/Git/usr/bin/bash.exe: no such file or directory
```

なお、Docker Desktop 上でコンテナの起動状況を確認しても起動はできていませんでした。

`make_env.sh` は事前に実行済みでしたが、`.env` の `UNAME=` が空の状況でした。

```
UID=1053158
GID=1049089
UNAME=
```

上記が問題でしょうか？

**Comment by msyksphinz-self** [comment]
返答遅れてしまい申し訳ありません。
ログを見ていて気になるのは、`C:/Program Files/Git/usr/bin/bash.exe`などのWindows上のプログラムが呼ばれています。これは、WSL上の環境でしょうか？
