### ISSUE TITLE
Rocket-ChipとBOOMのシュミレーション環境準備について

### ISSUE THREAD

**Issue by ghost** [msyksphinz-self/support_ca_llvm_book#25]
WSL の ubuntu20.04 を利用しています。
本の78ページを参考に Chipyard のインストールと、ツールチェインのビルドまでうまくいったのですが、
Rocket-Chip のシュミレーション環境を用意するためのコマンドを実行すると、エラーが発生します。

```
$ make CONFIG=RocketConfig
Makefile:5: *** Did not find Verilator in PATH. Make sure all requirements are installed.  Stop.
```

Chipyard のインストールをするために、下記コマンドを実行しました。

```
$ cd /tmp 
$ git clone https://github.com/ucb-bar/chipyard.git -b 1.7.1 --depth 1
$ cd chipyard
$ ./scripts/init-submodules-no-riscv-tools.sh
$ MAKEFLAGS="-j<ncores>" ./scripts/build-toolchains.sh riscv-tools --ignore-qemu
```

お手数ですが、対処法についてご教示いただけますと幸いです。
よろしくお願いいたします。

**Comment by msyksphinz-self** [comment]
ご確認ありがとうございます。
本書内にVerilatorのインストール方法について明確に記載しておりませんでした。
Chipyard-1.7.1を使用している場合、リポジトリ内にVerilatorをダウンロードしてインストールするスクリプトが含まれています。

Ubuntuを使用している場合、`scripts/ubuntu-req.sh`を参照してください。

```sh
# install verilator
git clone http://git.veripool.org/git/verilator
cd verilator
git checkout v4.034
autoconf && ./configure && make -j$(nproc) && sudo make install
```

**Comment by omchineko** [comment]
お返事いただきありがとうございます。
いただいた情報をもとに Verilator のインストールを行いましたところ、以下コマンドの実行はうまくいきました。

```
$ make CONFIG=RocketConfig
```

ただし、Rocket-Chip でシュミレーションを行うと、spike でのシュミレーション時と同じ結果が得られません。

```bash
$ ./simulator-chipyard-RocketConfig PK <gcd.cをコンパイルしたディレクトリ>/gcd.riscv
This emulator compiled with JTAG Remote Bitbang client. To enable, use +jtag_rbb_enable=1. 
Listening on port 44703
[UART] UART0 is here (stdin/stdout).  
simulator-chipyard-RocketConfig: ../fesvr/htif.h:35: T htif_t::from_target(target_endian<T>) const [with T = long unsigned int]: Assertion `endianness == memif_endianness_little || endianness == memif_endianness_big' failed. 
```

対応として[Chipyardのインストールについて](https://github.com/msyksphinz-self/support_ca_llvm_book/issues/14#issuecomment-1229117274)こちらの情報をもとに、RISCVのパスとツールチェインをChipyard内部のバイナリに差し替えたのですが、解決しませんでした。


度々お手数おかけして申し訳ありませんが、対処法についてご教示いただけますと幸いです。
よろしくお願いいたします。

**Comment by ghost** [comment]
ご回答いただきありがとうございます。
ご教示いただきました通り Verilator をダウンロードしたところ、
本の通りにコマンドを実行することができました。

丁寧にご対応いただきありがとうございました。
