### ISSUE TITLE
P.51 図２の出典が明記されていない。

### ISSUE THREAD

**Issue by hirooih** [msyksphinz-self/support_ca_llvm_book#26]
P. 51の図２とその下の説明で Embenchのcode sizeの結果が示されていますが、このデータは木村さんが測定したものでしょうか? それとも引用されたものでしょうか?
説明の流れからは  https://github.com/embench/embench-iot から引用した方に読めますが、このようなデータは見当たりません。
(https://github.com/embench/embench-iot-results にもありません。)

私が今まで見てきた評価結果と異なっているため、確認させてください。

**Comment by msyksphinz-self** [comment]
明確な参照元を記載しておらず申し訳ありません。これは筆者自身が測定した結果となっております。
より具体的には、以下の実験結果を参照ください。

https://msyksphinz.hatenablog.com/entry/2020/06/19/040000

**Comment by hirooih** [comment]
ありがとうございます。

> Cubicを抜いて全体のコードサイズを確認するとRV64GCの方が優れている。やはり実際にコードを確認してみると面白い。

私が今まで見てきたRISC-V関連の64bit CPUのbenchmark結果はLinux kernel, SPECなどのみで、Embenchの結果を見たことがなかったという事実に気が付きました。したがってこのEmbenchの結果は非常に貴重なものです。

P. 51脚注より

> この原因はABIがlong doubleをサポートしているかどうかで違いが現れるようです。

blogでも同様の表現がされていますが、「ABIでの long doubleの定義が異なるから」が正しい表現です。

https://github.com/embench/embench-iot/pull/18 より、

> On x86-64 it provides only 80 bits of precision, but on other architectures it provides either 64 bits or 128 bits of precision.

x86の80bit floatはIntelがIEEE floatをsupportする以前 8087 のときからのformatです。 (まだ現役だったことに少し驚いています。) ARMv8も念のため、versionは異なりますが手元の gccで blog と同じoption (`-march=armv8.4-a`) で以下の関数をcompileして確認してみました。

```c
long double add(long double a, long double b) {
    return a + b;
}
```
結果は以下です。

```sh
$ arm-none-eabi-gcc -march=armv8.4-a -Os -S -o - long_double.c
        .arch armv8.4-a
...
add:
...
        push    {r4, lr}
        bl      __aeabi_dadd
        pop     {r4, pc}
```

[fplib arithmetic on numbers in a particular format](https://developer.arm.com/documentation/dui0475/k/floating-point-support/fplib-arithmetic-on-numbers-in-a-particular-format) より、 aeabi_dadd doubleの加算です。
つまり ARM, x86が ISAがsupportしているformatであるのに対して、RISC-V ABI では128 floatと定義されているため、ずっと演算costの大きい処理での比較となっています。

Jeremy Bennettさんが

> because its ABI does not have explicit support for long double.

と回答していますが、 ここは "ABI" ではなく "ISA"  と書くべきところです。(そもそも報告者の指摘事項への回答になっていません。)

32bit CPUの Embenchの結果は見てきていますが、cubicの結果が悪いにせよ、全体のscoreにはP.51の結果ほど影響はでていません。32bit CPUの比較では、軽いにせよ Cortex M4 も doubleのsoftware emulationをするため,差がそれほど大きくなかったためと考えられます。

***

現在の表現では誤解する方が多くでてしまうと心配します。(私も周りに絶賛推薦中です:-))

- https://msyksphinz.hatenablog.com/entry/2020/06/19/040000 を引用
- long doubleがARMが64bit, x86が80bitと、それぞれnativeでsupportしているformatであるのに対して、[RISC-V ABI](https://github.com/riscv-non-isa/riscv-elf-psabi-doc/blob/master/riscv-cc.adoc#cc-type-details)ではISAがsupportしていない 128bitの formatを指定しているあること。
- (参考値として) cubicを除くと逆転すること。できれば除いたときの値を共有いただけると、とてもありがたいです。

***

あと P.23で Arm architectureとひとくくりにしていますが、https://people.eecs.berkeley.edu/~krste/papers/EECS-2016-1.pdf のなどにも書かれているように Arm architectureは様々な全く異なる ISA の総称です。昔からの ARMv[67]-A系, 組み込み向けの16bit命令のみ (正確には6命令ほど32bit命令を含む) ARMv[67]-M, 現在のスマホ、AppleのPCなどで使われている ARMv[89]-A の3つが代表的なものです。 P.23では必ずしもそこまで書く必要がないと思いますが、このbenchmarkの結果は ARMではなく　ARMv8-A と表記するのが良いと思います。

(実は、失礼にも Cortex-M4の数値と比較している可能性も考えていました。ごめんなさい。)

**Comment by msyksphinz-self** [comment]
コメントありがとうございます。正誤表のほうにもP.51の図に関して追加しました。

当時の測定データが出てきたのでそのままファイルを添付します。
(生データを公開したら問題あるかな...まいっか)

[tables.xlsx](https://github.com/msyksphinz-self/support_ca_llvm_book/files/9558804/tables.xlsx)

**Comment by hirooih** [comment]
> 正誤表のほうにもP.51の図に関して追加しました。

確認しました。苦労して言葉を練られた跡がうかがえます。ありがとうございます。

> (生データを公開したら問題あるかな...まいっか)

Proprietaryな compilerの場合は licenseをcheckする必要がありますが、gcc + Embenchのデータであれば問題ないと思います。

Cubicの影響が大きかった理由がわかりました。text sizeの合計値を比較しているようです。
Embenchの結果というのであれば、 (Spec benchmark同様) [geometric mean](https://en.wikipedia.org/wiki/Geometric_mean) の値である必要があります。https://github.com/embench/embench-iot-results#how-results-are-computed
Patterson先生に叱られます:-)

(以前Excelでgeometric meanの計算をする関数を探したのですが、見つけられませんでした。あったら教えていただきたいです。)

Spec BenchやLinux kernerlだとArmv8-Aに比べて RV64GCの方が明確に小さかったのですが、Embenchだとcubicを除いても、ほぼ同じなのですね。
これがあまり結果を見ない理由だったら、残念です。

**Comment by msyksphinz-self** [comment]
確かにちゃんと比較するためにはGeometric Meanでやらないとダメですね。これは私の評価が甘かったです。
(自分の本文を読み直すと「トータルのテキストサイズ」と書いてある...確か事実ではある、が、これだけでコード効率を語るのは早計ですね)

Excelだと`GEOMEAN()`でいけると思います。

**Comment by hirooih** [comment]
> ExcelだとGEOMEAN()でいけると思います。

 geometric standard deviation は `STDEV.P()` のようです。
計算しようと思ったのですが、まず [baseline (Coretex-M4) の値](https://github.com/embench/embench-iot-results/blob/master/details/cortexm4-armv7m-gcc-9.2-os.mediawiki) との比のgeometric meanと geometric standard deviation を取ることを思い出しました。
これは問題なかったのですが、libraryのtext code分を除くために embenchの `support/dummy-{crt0,libc,libgcc,ligm}.c` をcompileしたものを linkする必要があります。とりあえず今のままと思ってやってみたのですが、どう見てもlibrary分が含まれていて、library分の方が大きいものが多数あり、全く意味をなさないことが分かりました。
dataの取り直しが必要です。 そのうちなにかのEmbench値を測定するときがあったら、ついでに取ってここに報告しようと思います。(思い出すのに時間がかかりそう)

正誤表から参照されているこの threadを読んで正しい値でないことは分かれば十分ですので、closeしていただいて構いません。 改めてありがとうございました。

**Comment by hirooih** [comment]
@msyksphinz-self 

> そのうちなにかのEmbench値を測定するときがあったら、ついでに取ってここに報告しようと思います。

と書いて、半年ほど経ってしまいました。
以下の比較的新しい gcc を用いて Embench code size benchmark の結果を共有します。

- x86
  - gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0 : Ubuntu の default package
  - 'cflags' : '-Os -fno-stack-protector',
- armv8
  - https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloadsから binary download
  - aarch64-none-linux-gnu-gcc (Arm GNU Toolchain 12.2.Rel1 (Build arm-12.24)) 12.2.1 20221205
  - 'cflags' : '-Os -march=armv8.4-a'
- RISC-V
  - https://github.com/riscv-collab/riscv-gnu-toolchain から binary download
  - riscv64-unknown-elf-gcc (g2ee5e430018) 12.2.0
  - 'cflags' : '-Os -march=rv64gc'
  - 'cflags' : '-Os -march=rv64g'

https://github.com/embench/embench-iot-results に従い、libcなどは dummy の object を link。

### 絶対サイズ

![grouped-absolute-size](https://user-images.githubusercontent.com/24754036/232006455-69e3c8f4-0f5e-4092-ad75-8ce2c76af48b.svg)

- armv8-a の statemate の sizeが突出して大きい (この version の gcc の問題と思われる)
- P.51のグラフとの比較
  - 倍精度浮動小数演算のlibraryは除外されるため、cubicのscoreの悪化にはならない。
  - nettle-sha256 は使用される library のコードサイズが支配的だった模様。

### 相対サイズスコア (Cortex-M4との比)

![gm_gsd-relative-size](https://user-images.githubusercontent.com/24754036/232007181-e103bea9-0b80-4e82-a1cf-3b6a3be6661e.svg)

- RV64GC は 1.02 と、ほぼ Cortex-M4 に追いついている
  - コロナ前の RISC-V Worksop の時は、RISC-Vが20% ほど負けていたはず

### 相対サイズ (Cortex-M4との比)

![grouped-relative-size](https://user-images.githubusercontent.com/24754036/232007434-4fb605ba-5984-4d71-9bdd-26a07cf16f71.svg)

- やはり armv8-a の statemate の悪さが目立つ
- RISC-V は C-extension 必須
