### ISSUE TITLE
P99LLVMのコンパイルが失敗する

### ISSUE THREAD

**Issue by ghost** [msyksphinz-self/support_ca_llvm_book#27]
[RISCVアセンブリ生成が失敗してしまう #1](https://github.com/msyksphinz-self/support_ca_llvm_book/issues/1)

上記のissueを参考に、以下コマンドを実行してLLVMのビルドを行いました。

```
$cmake -G Ninja \
	-DDEFAULT_SYSROOT="${HOME}/riscv64_github/riscv64-unknown-elf" \
	-DCMAKE_BUILD_TYPE="Debug" -DLLVM_TARGETS_TO_BUILD="X86;RISCV" \
  -DLLVM_ENABLE_PROJECTS="clang;libcxx;libcxxabi" ../llvm
$ ninja -j1
```

その後、P99を参考に以下コマンドを実行しました。

```
${BUILD}/bin/clang x86_test.c -o x86_test_direct
```

すると以下のエラーが発生しました。

```
x86_test.c:1:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
```

すでに`-DDEFAULT_SYSROOT="${HOME}/riscv64_github/riscv64-unknown-elf`オプションを追加してLLVMをビルドしたのですが、エラーが解消されません。

お手数おかけして申し訳ありませんが、解決方法を教えていただけないでしょうか。

**Comment by msyksphinz-self** [comment]
返信遅れまして申し訳ありません。この問題はREADMEページの以下のページおよび、 #2 に記載しているのですが、正誤表に明示的に書いていなかったです。

https://github.com/msyksphinz-self/support_ca_llvm_book#llvm%E3%83%93%E3%83%AB%E3%83%89%E6%99%82%E3%81%AE%E6%8E%A8%E5%A5%A8%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3

x86とrisc-vでコンパイルする際に`-sysroot`を変更する必要があります。

> この場合、ホストがx86ならばビルドしたclangでx86をコンパイルする際(p.99)は-sysroot=/を付けなければ正しくx86のincludeファイルが読み込まれずにエラーになってしまうと思います。
