### ISSUE TITLE
LLVMのビルドをDebugビルドからReleaseビルド変更した場合に関して

### ISSUE THREAD

**Issue by m1goh** [msyksphinz-self/support_ca_llvm_book#28]
パソコンのメモリを16GBしか載せていません。WSLにmemory=16GBと手動でメモリサイズを16GBに固定しています。

P.158までのLLVMのビルドを試行してみました。DebugビルドだとNinjaでのビルドがメモリ不足（おそらく）で落ちてしまうのでReleaseビルドを試行してみました。こちらだと最後までビルドできます。
生成されたアセンブラのソースファイルは、P.159ページ出力されたsimple_func.myriscvx64.static.Sと同じものでした。このまま本を読み進めて作業をして確認をするのに本ではDebugビルドを指定していますがReleaseビルドを試行しても本と同じ結果が得られて問題はないでしょうか？もしうまくいかないようであればメモリを増設しようと思います。

Releaseビルドに変更して問題がないのか？Debugビルドにした方がよいのか？教えて下さい。よろしくお願いします。

**Comment by msyksphinz-self** [comment]
こちらは、メモリが足りない場合はReleaseビルドで問題ありません。生成される出力に違いはありません。
ただし、`llc`実行時のデバッグ情報が表示されなかったり、lldbなどでデバッグする際に正確な情報が出てこない場合があります。
