### ISSUE TITLE
LLVMのRyzen9 5750X 16コア32スレッドでのビルド時間について

### ISSUE THREAD

**Issue by m1goh** [msyksphinz-self/support_ca_llvm_book#29]
Ryzen7 3700X 8コア16スレッド 32GBのパソコンを使っています。

http://blog.kmckk.com/archives/5744578.html
こちらの記事では、WindowsでVisual Studioを使ってClangをRyzen9 5750X 16コア32スレッドでLLVMを
ビルドしているようですが、数分でビルドできると書いてあります。本では、WSLを使用しています。

以前、技術評論社に、LLVMのビルドにどの位メモリがあればいいか質問したところ
著者様から、コア数メモリは、あればあるほど良いと思いますと、
技術評論社経由で質問の返事をいただきました。
実際に、自分でLLVMをビルドしてみるとその通りなんだろうと思います。

本のP.96ページのLLVMのビルドをするのに家の環境だと50分位かかります。
ビルドが数分で終わるならば勉強の効率がよくなっていいと思います。
CPUを、5750Xに乗せ換えてみようかと思いますが、本当に数分でビルドできるのものでしょうか？

わかる範囲でいいので、アドバイスをいただけるとありがたいです。よろしくお願いします。

**Comment by msyksphinz-self** [comment]
実際に、私の手元でM1 MacBook Proで試行した結果数分でビルドできたことはあります。
手元のCore i7-1280PでWSL環境でも十数分レベルです。
なので数分というのは現実的な数値だと思います。

**Comment by m1goh** [comment]
返信ありがとうございます、参考になりました。
