### ISSUE TITLE
誤記？ 基本命令フォーマットの図(P.54の図4, P.133の図14)について

### ISSUE THREAD

**Issue by spinylobster** [msyksphinz-self/support_ca_llvm_book#34]
P.54の「図4:RISC-Vの基本命令フォーマット」の上には0から31までのビット位置を表す数字が区切りに合わせて振られていると思うのですが、そうすると19の次は22ではなく20であるべきではないでしょうか？

それと、26と27が何のために記されているのか分かりませんでした。これは消し忘れではないですか？

またP.133の「図14:RISC-Vの基本命令フォーマット」には31が2つありますが、右の方は30の間違いだと思います。

(図の解釈が間違っていたらすみません)

**Comment by spinylobster** [comment]
(ここの疑問は解決しました)

~~ビット表記についても、P.54とP.133でB-typeとJ-typeの即値immのビット表記が他と違って0始まりではなく1始まりになっているのは表記ミスではないでしょうか？
少なくともコード中では全て0始まりで統一されているようにみえます。
https://github.com/msyksphinz-self/llvm-project/blob/llvm-myriscvx120/llvm/lib/Target/MYRISCVX/MYRISCVXInstrFormats.td#L180-L187
また、U-typeの即値がimm[31:12]となっていますが、imm[19:0]ではないかと思いました。~~

~~P.55のColumnの図Bに関しても表記が間違っているせいか、即値のビット数が0ビット目と合わせて21bitになっています。~~

**Comment by spinylobster** [comment]
> P.55のColumnの図Bに関しても表記が間違っているせいか、即値のビット数が0ビット目と合わせて21bitになっています。

これについてはP.170のJAL命令の動きを読むことで納得できました。これは表記ミスではないのですね。
命令サイズが2バイトか4バイトしかないので、0bit目は常に0で良いということだと理解しました。

> ビット表記についても、P.54とP.133でB-typeとJ-typeの即値immのビット表記が他と違って0始まりではなく1始まりになっているのは表記ミスではないでしょうか？
少なくともコード中では全て0始まりで統一されているようにみえます。
https://github.com/msyksphinz-self/llvm-project/blob/llvm-myriscvx120/llvm/lib/Target/MYRISCVX/MYRISCVXInstrFormats.td#L180-L187

こちらも同様に、B-typeとJ-typeは共にジャンプ命令なので、RISC-Vの命令サイズ的に即値が奇数であることはあり得ないので、0bit目は常に0で問題ないと理解できました。

> また、U-typeの即値がimm[31:12]となっていますが、imm[19:0]ではないかと思いました。

これはP.198の定数生成を読むと理解できました。
上位20bitの即値を扱う命令と下位12bitの即値を扱う命令を組み合わせて任意の数値を生成する仕組みになっているのですね。

**Comment by msyksphinz-self** [comment]
返信遅れまして申し訳ありません。こちらは仰る通り誤記です。
正誤表に追記しました。

**Comment by spinylobster** [comment]
ありがとうございます。issueは閉じておきます。
