### ISSUE TITLE
ビルドエラーがおきるようです

### ISSUE THREAD

**Issue by pekujapan** [msyksphinz-self/support_ca_llvm_book#39]
Ubuntu18.04LTS, dockerでトライしているのですが、ninjaや環境変数がないらしい等エラーになるようです。
まず、ninjaのインストールやろうとすると、root権限がないことや sudoがない等進めない状態です
正しいやり方をご教示いただけると助かります。
llvm-user@4155c3d683c7:/llvm_book/llvm-project$ cd build/
llvm-user@4155c3d683c7:/llvm_book/llvm-project/build$  cmake -G Ninja -DCMAKE_BUILD_TYPE="Debug" \
>         -DLLVM_TARGETS_TO_BUILD="X86;RISCV" \
>         -DLLVM_ENABLE_PROJECTS="clang;libcxx;libcxxabi" \
>         ../llvm
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_ASM_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/llvm_book/llvm-project/build/CMakeFiles/CMakeOutput.log".
lvm-user@4155c3d683c7:/llvm_book/llvm-project/build/CMakeFiles$ cat CMakeOutput.log 
The system is: Linux - 5.4.0-150-generic - x86_64

sudo使えない, suのパスワードもわからない  ningaインストールできない
llvm-user@4155c3d683c7:/llvm_book/cmake-3.24.0$ sudo apt -y install ninja-build

**Comment by msyksphinz-self** [comment]
連絡ありがとうございます。
調査したところ、こちらで提供しているDockerのubuntu 18.04LTS版で、`ninja-build` パッケージがインストールされていないことが問題のようです。
https://github.com/msyksphinz-self/support_ca_llvm_book/blob/main/docker/ubuntu_1804_base/Dockerfile の14行目にはninja-buildが入っていませんが、
https://github.com/msyksphinz-self/support_ca_llvm_book/blob/main/docker/ubuntu_2204_base/Dockerfile の14行目にはninja-buildが入っています。この差分により、ubuntu 18.04でビルドができない原因となっています。

現在ubuntu 18.04のDockerコンテナを再構築中ですが、もしすぐに試したいとのことでしたら、Ubuntu 22.04 LTS版をご利用ください。

Ubuntu 18.04LTS版で再構築が完了したら、このIssue内でお知らせします。

**Comment by msyksphinz-self** [comment]
新Dockerイメージを作成したので、お手数ですが再試行していただけませんでしょうか？

**Comment by pekujapan** [comment]
ご対応ありがとうございます。
無事にビルドできたようです。
(new issueがありますので、お手数ですがご対応いただけますでしょうか)
