### ISSUE TITLE
誤記報告：P33のメモリストア命令の記述について

### ISSUE THREAD

**Issue by komainu8** [msyksphinz-self/support_ca_llvm_book#4]
P33のメモリストア命令の説明に「それぞれ32ビット、8ビット、16ビットのデータを読み出す例です。」と記載されていますが、ストア命令ですので、「データを読み出す例」ではなく、「データをストアする例」ではないでしょうか？

誤記ではないかと思われるのでご報告いたします。
私の勘違いで誤記ではなかったらすみません。

**Comment by msyksphinz-self** [comment]
ありがとうございます。ご指摘の通りです。
正誤表に追記しました。

**Comment by komainu8** [comment]
ご対応ありがとうございます！

まだ最初の方ですが、とてもわかりやすく、楽しんで読ませていただいております！
