### ISSUE TITLE
LLVMのバックエンドを作るための第一歩の章について

### ISSUE THREAD

**Issue by tichkr** [msyksphinz-self/support_ca_llvm_book#5]
Triple.cppとMYRISCVX.tdが、書籍に記載されているコードとgithubに登録されているコードで差分があります。
意図的に記載内容を省略しているようでしたらすみません。

Triple.cpp：
書籍では、StringRef Triple::getArchTypeName(ArchType Kind)の修正箇所のみ記載されているが、githubにあるコードではその他の複数箇所にmyriscvx32とmyriscvx64が追加されています。
https://github.com/msyksphinz-self/llvm-project/commit/2467c9de633932bd9f77285b3af053a82e682e82#diff-a6431c77551c3d00b1ac20938a6a95bd3f50c5ed7d126e7f25b5b55fe55767c7

MYRISCVX.td：
書籍では、def Targetのみが記載されているが、githubにあるコードでは各種includeやMYRISCVXInstrInfoの定義があります。
https://github.com/msyksphinz-self/llvm-project/commit/2467c9de633932bd9f77285b3af053a82e682e82#diff-adfabc37f7c8aa94c320bd37652629ed165ba068a5f63e3e78033360ff537275

**Comment by msyksphinz-self** [comment]
ご指摘ありがとうございます。仰る通り、書籍ではソースコードの一部のみを抜粋し、要点のみを掲載しております。
すべての動作を再現したい場合、ご指摘の通りGitHubのソースコードを参照していただきますよう、よろしくお願いいたします。

**Comment by tichkr** [comment]
返答ありがとうございます。
再現するにはGitHubのコードを参照する必要があること、了解しました。
